# Generated by Django 5.0.4 on 2024-04-12 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('writer', models.CharField(max_length=20, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
