# Generated by Django 5.0.4 on 2024-04-12 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ft', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Board',
            new_name='FairyTale',
        ),
        migrations.RenameField(
            model_name='fairytale',
            old_name='writer',
            new_name='user',
        ),
    ]
