# Generated by Django 5.0.4 on 2024-04-12 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ft', '0004_remove_fairytale_id_fairytale_fairytale_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fairytale',
            name='fairytale_id',
        ),
        migrations.AddField(
            model_name='fairytale',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
