# Generated by Django 5.0.4 on 2024-04-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ft', '0006_remove_fairytale_id_fairytale_fairytale_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fairytale',
            name='user',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
