# Generated by Django 5.0.4 on 2024-04-12 05:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ft', '0009_alter_fairytale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fairytale',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
