# Generated by Django 5.0.4 on 2024-04-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ft', '0011_alter_fairytale_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fairytale',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
